website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from . import db
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    # redirects already logged in users to the home page
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Login successfully!', category='sucess')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password, try again..', category='error')
        else:
            flash('User does not exists..', category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been successfully logged out..', category='success')
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        email = request.form.get('email')   
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email is already taken!', category='error')

        elif len(email) < 4:
            flash('Email too short', category='error')
            
        elif len(username) < 2:
            flash('Username should be more than 1 character', category='error')

        elif len(password) < 6:
            flash('Password should be more than 6 characters', category='error')
            
        else:
            # this will create a new user
            new_user = User(
                email=email, 
                username=username, 
                password=generate_password_hash(password)
            )
            db.session.add(new_user)                #add new user to the database
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created successfully!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign-up.html", user=current_user)

website/views.py
from flask import Blueprint, abort, redirect, render_template, request, flash, jsonify, url_for
from flask_login import login_required, current_user
from . import db
from .models import User, Note
import json

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)

@views.route('/study-tools/notes')
def studytools():
    return render_template("study-tools.html", user=current_user)

@views.route('/coming-soon')
def comingsoon():
    return render_template("coming-soon.html", user=current_user)

# route for notes (includes add, edit, delete and view notes)
@views.route('/study-tools/notes/<int:note_id>', methods=['GET', 'POST'])
@login_required
def show_notes(note_id):
    note = Note.query.get(note_id)

    if not note:    
        flash('Note not found', category='error')
        return redirect(url_for('views.studytools'))  # this will redirect to notes list
    
    if note.user_id != current_user.id:
        flash('You do not have permission to view this note', category='error')
        return redirect(url_for('views.studytools'))

    notes_list = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("study-tools.html", notes=notes_list, current_note=note, user=current_user)


@views.route('study-tools/notes/new', methods=['GET', 'POST'])
@login_required
def add_note():
    if request.method == "POST":
        note = request.form.get('note')
        title = request.form.get('title')

        if not note:
            flash('..It\'s empty?', category='error')

        elif not title:
            flash('Please add a title to your note.', category='error')

        else:
            new_note = Note(note_data=note, title=title, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note saved!', category='success')
            return redirect(url_for('views.studytools'))

    return render_template("add-note.html", user=current_user)


@views.route('study-tools/notes/edit/<int:note_id>', methods=['GET', 'POST'])
def edit_note(note_id):
    note = Note.query.get(note_id)

    if not note:
        flash('Note not found', category='error')
        return redirect(url_for('views.studytools'))  # this will redirect to notes list
    
    if note.user_id != current_user.id:
        flash('You do not have permission to edit this note', category='error')
        return redirect(url_for('views.studytools'))

    if request.method == "POST":
        edit_note = request.form.get('note')
        edit_title = request.form.get('title')

        if not edit_note or not edit_title:
            if not note:
                flash('..It\'s empty?', category='error')  #this will return to the edit mode for the note if input is empty 

            if not edit_title:
                flash('Please add a title to your note.', category='error')
            
            return render_template("edit-note.html", user=current_user, notes=Note.query.filter_by(user_id=current_user.id).all(), current_note=note)

        else:
            note.note_data = edit_note
            note.title = edit_title
            db.session.commit()
            flash('Changes saved successfully!', category='success')
            return redirect(url_for('views.show_notes', note_id=note_id))     #if saved successfully, it will show the note
    

    notes_list = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("edit-note.html", user=current_user, notes=notes_list, current_note=note)     #this will render the edit_note.html and it will pass those variables to that html

@views.route('study-tools/notes/delete/<int:note_id>', methods=['GET'])
def delete_note(note_id):
    note = Note.query.get(note_id)

    if not note:
        flash('Note not found', category='error')

    else:
        db.session.delete(note)
        db.session.commit()
        flash('Note Deleted!', category='success')
    return redirect(url_for('views.studytools'))


@views.route('/search', methods=['GET'])
def search():
    query = request.args.get('s')  # get the search query from the URL parameter
    results = []

    if query and current_user.is_authenticated:
        # search for notes containing the query
        results = Note.query.filter(
            (Note.title.ilike(f"%{query}%")) | (Note.note_data.ilike(f"%{query}%"))
        ).filter_by(user_id=current_user.id).all()
    
    elif not current_user.is_authenticated:
        flash('You need to be logged in to search notes', category='error')
        return redirect(url_for('auth.login'))

    return render_template('search.html', query=query, results=results, user=current_user)

website/templates/add-note.html
{% extends "base.html" %}
{% block title %}Add New Note{% endblock %}
{% block css %}
<link href="{{ url_for('static', filename='css/notes.css') }}" rel="stylesheet">
<style>
    body{
        background-color: #F3E5F5;
    }
    .container#content{
        background-color: #f3f3f3;
        min-height: 80vh;
    }
    body.dark-mode input{
      background-color: #d1d1d1;
      color: #2c2c2e;
    }
    body.dark-more input:active {
      background-color: #d1d1d1;
      color: #2c2c2e;
    }

</style>
{% endblock %}

{% block content %} 

<section class="pt-3">
  <div class="container shadow section-custom rounded" id="content">
    <div class="row">
      <!-- sidebar -->
      <div class="col-lg-3">
        <ul class="sidenav">
          <li title="Notes" class="sidelist parent active">
            <a href="{{ url_for('views.studytools')}}">Notes</a>
            <ul>
              <li class="sidelist item">
                <a class="list-group-item list-group-item-action custom-green-300"
              href="{{ url_for('views.add_note')}}"><i class="bi bi-plus-lg"></i>
                Add New Note
                </a>
              {% for note in user.notes %}
              <li class="sidelist item">
                <a href="{{ url_for('views.show_notes', note_id=note.id) }}" data-note-id="{{ note.id }}">{{ note.title }}
                </a>
              {% endfor %}
              </li>
            </ul>
          </li>
      </div>

      <!-- body -->
      <div class="col-lg-8">
          <!-- main content -->
        <form method="POST">
          <div class="d-flex justify-content-between align-items-center mb-4">
              <h5 class="font-weight-medium">Add Note</h5>
              <button type="submit" class="btn btn-success" id="submitBtn">Save</button>
          </div>
          
          <div class="content">
              <div class="container-fluid mt-3">
                  <label for="title" class="form-label">
                      Title</label>
                  <input type="text" class="form-control" id="title" name="title" placeholder="Enter title here..." autofocus="true"> <br/> 
                  
                  <textarea name="note" id="note" class="form-control" placeholder="Write here..."></textarea> <br/>
              </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>    

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-name" content="godocs" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/themify-icons/themify-icons.css') }}">

    <!-- Main Stylesheet -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/darkmode.css') }}" rel="stylesheet">

    <!--Favicon-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/lf.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='images/lf.ico') }}" type="image/x-icon">
    
    {% block css %}{% endblock %}

</head>
<body>
  <header class="sticky-top navigation navbar-dark px-5">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand text-light" href="{{ url_for('views.home') }}">
            <!-- <img src="/" alt="Logo" width="30" height="24" class="d-inline-block align-text-top"> -->
            <i class="bi bi-clipboard-heart" style="font-size: 30px;"></i>
            StudyPal
          </a>
          <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-expanded="false">
            <i class="ti-align-right h4 text-light"></i>
          </button>
          
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ms-auto align-items-center">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.studytools')}}">Notes</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item dropdown list-unstyled">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform:none">{{user.username}}</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <!-- <a class="dropdown-item" href="#!">Account</a>
                  <div class="dropdown-divider"></div> -->
                  <a class="dropdown-item" id="logout" href="/logout">Logout</a>
                </ul>
              </li>

              {% else %}
              <!-- Sign Up and Login buttons -->
              <li class="nav-item">
                <a href="{{ url_for('auth.signup') }}" class="btn btn-sm btn-outline-primary ms-lg-4">Sign Up</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('auth.login') }}" class="btn btn-sm btn-primary ms-lg-4">Login</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <button id="darkModeToggle" class="btn btn-sm btn-outline-secondary ms-lg-4" aria-label="Toggle Dark Mode" title="Enter Dark Mode"><i class="bi bi-cloud-sun-fill"></i></button>
              </li>
            </ul>
          </div>
        </nav>
      </div>
  </header>
    
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show m-0" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% else %}
            <div class="alert alert-success alert-dismissible fade show m-0" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}


    <footer>
        <div class="container">
          <div class="row align-items-center border-bottom py-5">
          </div>
          <div class="py-4 text-center">
            <div class="mb-4 mb-lg-0">
              <a class="navbar-brand" href="{{ url_for('views.home') }}">
                <i class="bi bi-clipboard-heart" style="font-size: 30px;"></i>
                  <h3>StudyPal</h3>
               <!-- <img class="img-fluid" src="{{ url_for('static', filename='/images/logo.png') }}" alt="StudyPal"> -->
              </a>
            </div>
            <small class="text-dark">Copyright © 2025 StudyPal</small>
          </div>
        </div>
    </footer>

    <!-- plugins -->
    <script src="{{ url_for('static', filename='plugins/jQuery/jquery.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='plugins/masonry/masonry.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/clipboard/clipboard.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/match-height/jquery.matchHeight-min.js') }}"></script>

    <!-- Main Script -->
    <script src="{{ url_for('static', filename='script.js') }}"></script>
    <script src="{{ url_for('static', filename='index.js') }}"></script>
    
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toggleDark = document.getElementById('darkModeToggle');
            const body = document.body;
            const icon = toggleDark.querySelector('i'); // select the icon inside the button
    
            // apply dark mode if saved in localStorage
            if (localStorage.getItem('darkMode') === 'enabled') {
                body.classList.add('dark-mode');
                icon.className = 'bi-moon-stars-fill'
            }
    
            toggleDark.addEventListener('click', function () {
                body.classList.toggle('dark-mode');
                if (body.classList.contains('dark-mode')) {
                    localStorage.setItem('darkMode', 'enabled');
                    icon.className = 'bi-moon-stars-fill'
                    this.setAttribute('title', 'Exit Dark Mode');
                } else {
                    localStorage.setItem('darkMode', 'disabled');
                    icon.className = 'bi-cloud-sun-fill'
                    this.setAttribute('title', 'Enter Dark Mode');
                }
            });
        });
    </script>

</body>
</html>

website/templates/calendar.html
{% extends "base.html" %}
{% block title %}Schedule{% endblock %}

{% block content %}
<div id="calendar"></div>






<script>
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: 'dayGridMonth'
    });
    calendar.render();
  });
</script>  
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js"></script>
{% endblock %}

website/templates/coming-soon.html
{% extends "base.html" %}
{% block title %}Coming Soon{% endblock %}
{% block css %}

  <!-- Main CSS File -->
  <link href="{{ url_for('static', filename='css/coming-soon.css') }}" rel="stylesheet">

  <style>
    body {
      background: ("{{ url_for('static', filename='images/bg.jpg') }}") top center no-repeat;
    }
    .footer-menu, .text-dark {
      color: #fff !important;
    }

  </style>



  <!-- =======================================================
  * Template Name: Maundy
  * Template URL: https://bootstrapmade.com/maundy-free-coming-soon-bootstrap-theme/
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  
{% endblock %}
{% block content %}
  <main class="main">
    <!-- Hero Section -->
    <section id="hero" class="hero section">
      <div class="container text-center">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <h1>StudyPal<br></h1>
            <p>We are still working on this feature. Stay tuned for updates!</p>
          </div>
          <div class="countdown d-flex justify-content-center" data-count="2025/5/26">
            <div>
              <h3 class="count-days">482</h3>
              <h4>Days</h4>
            </div>
            <div>
              <h3 class="count-hours">6</h3>
              <h4>Hours</h4>
            </div>
            <div>
              <h3 class="count-minutes">49</h3>
              <h4>Minutes</h4>
            </div>
            <div>
              <h3 class="count-seconds">21</h3>
              <h4>Seconds</h4>
            </div>
          </div>
      <!--
          <div class="col-lg-5 hero-newsletter">
            <p>Subscribe now to get the latest updates!</p>
            <form action="forms/newsletter.php" method="post" class="php-email-form">
              <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your subscription request has been sent. Thank you!</div>
            </form>
          </div>     -->
        </div>
      </div>

    </section><!-- /Hero Section -->


  </main>


  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Main JS File -->
  <script src="{{ url_for('static', filename='coming-soon.js') }}"></script>
  
{% endblock %}

website/templates/edit-note.html
{% extends "base.html" %}
{% block title %}Add New Note{% endblock %}
{% block css %}
<link href="{{ url_for('static', filename='css/notes.css') }}" rel="stylesheet">
<style>
    body{
        background-color: #F3E5F5;
    }
    .container#content{
        background-color: #f3f3f3;
        min-height: 80vh;
    }
</style>
{% endblock %}

{% block content %}
<section class="pt-3">
  <div class="container shadow section-custom rounded" id="content">
    <div class="row">
      <!-- sidebar -->
      <div class="col-lg-3">
        <ul class="sidenav">
          <li title="Notes" class="sidelist parent active">
            <a href="{{ url_for('views.studytools')}}">Notes</a>
            <ul>
              <li class="sidelist item">
                <a class="list-group-item list-group-item-action custom-green-300"
              href="{{ url_for('views.add_note')}}"><i class="bi bi-plus-lg"></i>
                Add New Note
                </a>
              {% for note in user.notes %}
              <li class="sidelist item">
                <a href="{{ url_for('views.show_notes', note_id=note.id) }}" data-note-id="{{ note.id }}">{{ note.title }}
                </a>
              {% endfor %}
              </li>
            </ul>
          </li>
      </div>

      <!-- body -->
      <div class="col-lg-8">
          <!-- main content -->
        <form method="POST">
          <div class="d-flex justify-content-between align-items-center mb-4">
              <h5 class="font-weight-medium">Edit Note</h5>
              <button type="submit" class="btn btn-success" id="submitBtn">Save</button>
          </div>

        <div class="content">
            {% if current_note %}
              <div class="container-fluid mt-3">
                  <label for="title" class="form-label">
                      Title</label>
                  <input type="text" class="form-control" id="title" name="title" value="{{current_note.title}}" autofocus="true"> <br/> 
                  
                  <textarea name="note" id="note" class="form-control" placeholder="Write here...">{{current_note.note_data}}</textarea> <br/>
              </div>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
</section>    

{% endblock %}

website/templates/flashcards.html
{% extends "base.html" %}
{% block title %}Flashcards{% endblock %}
{% block css %}
<link href="{{ url_for('static', filename='css/notes.css') }}" rel="stylesheet">


<style>
    body{
        background-color: #F3E5F5;
    }
    .container-fluid#content{
        background-color: #f3f3f3;
        min-height: 90vh;
    }

    .flashcard {
        width: 370px;
        height: 200px;
        margin: 10px;
        padding: 20px;
        border: 1px solid #b9b9b9;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        display: inline-block;
    }
    .flashcard .question {
        font-weight: bold;
        font-size: 18px;
    }
    .flashcard .answer {
        font-size: 16px;
        display: none;
    }
    .flashcard:hover .answer {
        display: block;
    }
    </style>

{% endblock %}
{% block content %}

<section class="pt-3">
    <div class="container-fluid shadow section-custom rounded" id="content">
      <div class="row">
        <!-- sidebar -->
        <div class="col-lg-3">
          <ul class="sidenav">
            <li class="sidelist parent active">
              <a href="{{ url_for('views.studytools')}}">Notes</a>
              <ul>
                <li class="sidelist item">
                  <a class="list-group-item list-group-item-action custom-green-300"
                href="{{ url_for('views.flashcards')}}"><i class="bi bi-plus-lg"></i>
                  Create New Flashcard
                  </a>
                {% for flashcard in user.flashcards %}
                <li class="sidelist item">
                  <a href="{{ url_for('views.flashcards', id=flashcard.id) }}">{{ flashcard.question }}</a>
                {% endfor %}
                </li>
              </ul>
            </li>
        </div>
  
        <!-- body -->
        <div class="col-lg-8">
          <div class="px-lg-3 px-3">
            <!-- main content -->
            <h1>Flashcards</h1>
            <div class="content flashcards-container" >
                {% for flashcard in flashcards %}
                <div class="flashcard">
                    <div class="question">{{ flashcard.question }}</div>
                    <div class="answer">{{ flashcard.answer }}</div>
                </div>
                {% endfor %}
              <!-- add flashcards -->

                <form method="POST">
                    <input type="text" id="question" name="question" placeholder="Question">
                    <input type="text" id="answer" name="answer" placeholder="Answer">
                    <button type="submit">Add Flashcard</button>
                </form>
            </div>
        </div>
      </div>
    </div>
</section>




{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block css %}
<!-- <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css"> -->
<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.4/components/registrations/registration-3/assets/css/registration-3.css">
{% endblock %}

{% block content %}
<!-- Registration 3 - Bootstrap Brain Component -->
<section class="p-3 p-md-4 p-xl-5">
    <div class="container signup-card card">
      <div class="row">
        <div class="col-12 col-md-6">
          <div class="d-flex flex-column justify-content-between h-100 p-3 p-md-4 p-xl-5">
            <h3 class="m-0">Welcome!</h3>
            <img src="{{ url_for('static', filename='images/study.png') }}" class="img-fluid" alt="Welcome">
            <p class="mb-0">Not a member yet? <a href="{{ url_for('auth.signup') }}" class="link-secondary text-decoration-none">Sign up now</a></p>
          </div>
        </div>
        <div class="col-12 col-md-6">
          <div class="p-3 p-md-4 p-xl-5">
            <div class="row">
              <div class="col-12">
                <div class="mb-5">
                  <h2 class="h3">Create your Account</h2>
                  <h3 class="fs-6 fw-normal text-secondary m-0">Enter your details</h3>
                </div>
              </div>
            </div>
            <form method="POST">
              <div class="row gy-3 gy-md-4 overflow-hidden">
                <div class="col-12">
                  <label for="username" class="form-label">Username <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
                </div>
                <div class="col-12">
                  <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
                </div>
                <div class="col-12">
                  <label for="password" class="form-label">Password <span class="text-danger">*</span></label>
                  <input type="password" class="form-control" name="password" id="password" value="" placeholder="Password" required>
                </div>
                <div class="col-12">
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" name="iAgree" id="iAgree" required>
                    <label class="form-check-label text-secondary" for="iAgree">
                      I agree to the <a href="#!" class="link-primary text-decoration-none">terms and conditions</a>
                    </label>
                  </div>
                </div>
                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn bsb-btn-xl btn-primary" type="submit">Sign up</button>
                  </div>
                </div>
              </div>
            </form>
            <div class="row">
              <div class="col-12">
                <hr class="mt-5 mb-4 border-secondary-subtle">
                <p class="m-0 text-secondary text-end">Already have an account? <a href="{{ url_for('auth.login') }}" class="link-primary text-decoration-none">Log in</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

website/templates/study-tools.html
{% extends "base.html" %}
{% block title %}Notes{% endblock %}
{% block css %}
<link href="{{ url_for('static', filename='css/notes.css') }}" rel="stylesheet">

<style>
  body{
    background-color: #F3E5F5;
  }
  .container#content{
    background-color: #f3f3f3;
    min-height: 80vh;
  }
  .bi-trash:hover {
    color: rgb(204, 9, 9);
  }
  .bi-trash {
    color: rgb(153, 14, 14);
  }
</style>

{% endblock %}

{% block content %}
    <!-- details page -->
<section class="pt-3">
    <div class="container shadow section-custom rounded" id="content">
      <div class="row">
        <!-- sidebar -->
        <div class="col-lg-3">
          <ul class="sidenav">
            <li class="sidelist parent active">
              <a href="{{ url_for('views.studytools')}}">Notes</a>
              <ul>
                <li class="sidelist item">
                  <a class="list-group-item list-group-item-action custom-green-300"
                href="{{ url_for('views.add_note')}}"><i class="bi bi-plus-lg"></i>
                  Add New Note
                  </a>
                {% for note in user.notes %}
                <li class="sidelist item">
                  <a href="{{ url_for('views.show_notes', note_id=note.id) }}" data-note-id="{{ note.id }}">{{ note.title }}</a>
                {% endfor %}
                </li>
              </ul>
            </li>
        </div>
  
        <!-- body -->
        <div class="col-lg-8">
          <div class="px-lg-3 px-3">
            <!-- main content -->
          {% if current_note %}
            <h3 class="font-weight-medium" id="note-title">{{ current_note.title }}
              <a href="{{ url_for('views.delete_note', note_id=current_note.id) }}"><i class="bi bi-trash float-end ps-3" style="font-size: 20px;"></i>
              <a href="{{ url_for('views.edit_note', note_id=current_note.id) }}"><i class="bi bi-pencil-fill float-end" style="font-size: 20px;"></i>
              </a></h3>
            <div class="content" id="note-content">
              <pre class="text-break">{{ current_note.note_data }}</pre>
              <!-- navigation -->
            </div>
          {% else %}
            <style>
              #cloud{
                  width: 200px;
                  height: auto;
                  text-align: center;
                  padding-top: 50px
              }
            </style>
            <figure class="figure mx-auto d-block">
              <img src="{{ url_for('static', filename='images/cloud.png') }}" class="figure-img img-fluid mx-auto d-block" alt="cloud" id="cloud" draggable="false">
              <figcaption class="figure-caption text-center">Select a note from the sidebar to view...</figcaption>
            </figure>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
</section>


{% endblock %}